# Quantitative Momentum Strategy

"Momentum investing" means investing in the stocks that have increased in price the most.

For this project, we're going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.


## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
import numpy as np
import pandas as pd
import requests 
import xlsxwriter 
import math 
from io import StringIO
from scipy import stats 
import yfinance as yf

## Importing Our List of Stocks

As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the `.csv` file is still in your working directory and import it with the following command:

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

response = requests.get(url, headers=headers)

# Wrap response.text in StringIO()
# This prevents the FileNotFoundError by telling pandas: "This is a stream of text"
data_stream = StringIO(response.text)
sp500_table = pd.read_html(data_stream)

stocks = sp500_table[0]
stocks.rename(columns={'Symbol': 'Ticker'}, inplace=True)
stocks['Ticker'] = stocks['Ticker'].str.replace('.', '-', regex=False)

## Making Our First API Call

It's now time to make the first version of our momentum screener!

We need to get one-year price returns for each stock in the universe. Here's how.

In [3]:
symbol = 'AAPL' 
api_url = yf.Ticker(symbol) 
data = api_url.info 
data

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 166000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 55,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1970,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1777593600,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 298.87,
 'open': 299.82,
 'dayLow': 295.38,
 'dayHigh': 300.35,
 'regularMarketPreviousClose': 298.87,
 'regularMarketOpen': 299.82,
 'regularMarketDayLow': 295.38,
 'regularMarketDayHigh': 300.35,
 'dividendRate': 1.08,
 'dividendYield': 0.36,
 'exDividendDate': 1778457600,
 'payoutRatio': 0.1259,
 'fiveYearAvgDividendYield': 0.51,
 'beta': 1.065,
 'trailingPE': 36.102905,
 'forwardPE': 31.108585,
 'volume': 33673067,
 'regularMarketVolume': 33673067,
 'averageVolume': 43612950,
 'averageVolume10days': 50809180,
 'averageDailyVolume10Day': 50809180,
 'bid': 298.0,
 'ask': 298.08,
 'bidSize': 4,
 'askSize': 16,
 'marketCap': 4379916369920,
 'nonDilutedMarketCap': 4308095261920,
 'fiftyTwoWeekLow': 193.46,
 'fiftyTwoWeekHigh': 300.92,
 'allTimeHigh': 300.92,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 9.702058,
 'fiftyDayAverage': 265.3904,
 'twoHundredDayAverage': 258.67654,
 'trailingAnnualDividendRate': 1.04,
 'trailingAnnualDividendYield': 0.0034797736,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4396120539136,
 'profitMargins': 0.27152002,
 'floatShares': 14662534368,
 'sharesOutstanding': 14687356000,
 'sharesShort': 134675274,
 'sharesShortPriorMonth': 126771284,
 'sharesShortPreviousMonthDate': 1774915200,
 'dateShortInterest': 1777507200,
 'sharesPercentSharesOut': 0.0092,
 'heldPercentInsiders': 0.01633,
 'heldPercentInstitutions': 0.65384,
 'shortRatio': 3.11,
 'shortPercentOfFloat': 0.0092,
 'impliedSharesOutstanding': 14687356000,
 'bookValue': 7.26,
 'priceToBook': 41.075756,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1774656000,
 'earningsQuarterlyGrowth': 0.194,
 'netIncomeToCommon': 122575003648,
 'trailingEps': 8.26,
 'forwardEps': 9.5861,
 'pegRatio': 2.61,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 9.738,
 'enterpriseToEbitda': 27.48,
 '52WeekChange': 0.41157818,
 'SandP52WeekChange': 0.2589395,
 'lastDividendValue': 0.27,
 'lastDividendDate': 1778457600,
 'quoteType': 'EQUITY',
 'currentPrice': 298.21,
 'targetHighPrice': 400.0,
 'targetLowPrice': 215.0,
 'targetMeanPrice': 308.06512,
 'targetMedianPrice': 310.0,
 'recommendationMean': 1.95833,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 43,
 'totalCash': 68507000832,
 'totalCashPerShare': 4.664,
 'ebitda': 159975997440,
 'totalDebt': 84710998016,
 'quickRatio': 0.906,
 'currentRatio': 1.07,
 'totalRevenue': 451442016256,
 'debtToEquity': 79.548,
 'revenuePerShare': 30.534,
 'returnOnAssets': 0.26229,
 'returnOnEquity': 1.4147099,
 'grossProfits': 216070995968,
 'freeCashflow': 101090746368,
 'operatingCashflow': 140222005248,
 'earningsGrowth': 0.218,
 'revenueGrowth': 0.166,
 'grossMargins': 0.47862,
 'ebitdaMargins': 0.35437,
 'operatingMargins': 0.32275,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'marketState': 'PRE',
 'cryptoTradeable': False,
 'corporateActions': [],
 'preMarketTime': 1778846055,
 'regularMarketTime': 1778788801,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'regularMarketChangePercent': -0.220833,
 'regularMarketPrice': 298.21,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'preMarketChange': -3.2999878,
 'preMarketChangePercent': -1.1065986,
 'preMarketPrice': 294.91,
 'regularMarketChange': -0.660004,
 'regularMarketDayRange': '295.38 - 300.35',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 43612950,
 'fiftyTwoWeekLowChange': 104.749985,
 'fiftyTwoWeekLowChangePercent': 0.5414555,
 'fiftyTwoWeekRange': '193.46 - 300.92',
 'fiftyTwoWeekHighChange': -2.710022,
 'fiftyTwoWeekHighChangePercent': -0.009005789,
 'fiftyTwoWeekChangePercent': 41.157818,
 'dividendDate': 1778716800,
 'earningsTimestamp': 1777579200,
 'earningsTimestampStart': 1785441600,
 'earningsTimestampEnd': 1785441600,
 'earningsCallTimestampStart': 1777582800,
 'earningsCallTimestampEnd': 1777582800,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 8.26,
 'epsForward': 9.5861,
 'epsCurrentYear': 8.73406,
 'priceEpsCurrentYear': 34.14334,
 'fiftyDayAverageChange': 32.81958,
 'fiftyDayAverageChangePercent': 0.12366528,
 'twoHundredDayAverageChange': 39.533447,
 'twoHundredDayAverageChangePercent': 0.15282966,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.0 - Buy',
 'displayName': 'Apple',
 'trailingPegRatio': 2.5713}

## Parsing Our API Call

This API call has all the information we need. We can parse it using the same square-bracket notation as in the first project of this course. Here is an example.

In [4]:
data.get('fiftyTwoWeekChangePercent')

41.157818

## Executing A Batch API Call & Building Our DataFrame

Just like in our first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called `chunks` that we can use to divide our list of securities into groups of 100.

In [5]:
# # Function sourced from 
# # https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
# def chunks(lst, n):
#     """Yield successive n-sized chunks from lst."""
#     for i in range(0, len(lst), n):
#         yield lst[i:i + n]   
        
# symbol_groups = list(chunks(stocks['Ticker'], 100))
# symbol_strings = []
# for i in range(0, len(symbol_groups)):
#     symbol_strings.append(','.join(symbol_groups[i]))
# #     print(symbol_strings[i])

# my_columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [6]:
# price = data.get('currentPrice')
# market_cap = data.get('marketCap')

# my_columns = [ 'Ticker', 'Stock Price', 'Market Capitalisation', 'Number of Shares to Buy'] 
# final_dataframe = pd.DataFrame(columns = my_columns)  

# new_row = pd.Series([symbol, price, market_cap, 'N/A'], index = my_columns).to_frame().T
# final_dataframe = pd.concat([final_dataframe, new_row], ignore_index = True) 

# final_dataframe = pd.DataFrame(columns = my_columns) 
# for stock in stocks['Ticker']: 
#     api_url = yf.Ticker(stock) 
#     data = api_url.info 
#     new_row = pd.Series([stock, data.get('currentPrice'), data.get('marketCap'), 'N/A'], index = my_columns).to_frame().T 
#     final_dataframe = pd.concat([final_dataframe, new_row], ignore_index = True) 


# 1. Initialize the Tickers object with all symbols at once
# stocks['Ticker'] is your list from Wikipedia
tickers_list = stocks['Ticker'].tolist()
tickers_data = yf.Tickers(tickers_list)

rows_list = []

# print("Fetching data... this may take a minute.")

# 2. Loop through the tickers to get 'info'
# We use rows_list to avoid the slow pd.concat inside a loop
for symbol in tickers_list:
    try:
        # Accessing the individual ticker object from our batch
        ticker_info = tickers_data.tickers[symbol].info
        
        price = ticker_info.get('currentPrice') or ticker_info.get('regularMarketPrice')
        # market_cap = ticker_info.get('marketCap')
        one_year_price_return = ticker_info.get('fiftyTwoWeekChangePercent') 
        
        if price:
            rows_list.append({
                'Ticker': symbol,
                'Stock Price': price,
                'One-Year Price Return': one_year_price_return,
                'Number of Shares to Buy': 'N/A'
            })
    except Exception as e:
        # This skips tickers that might have been delisted mid-day or have errors
        continue

# 3. Create the final DataFrame in one go
final_dataframe = pd.DataFrame(rows_list)

final_dataframe

    Ticker  Stock Price  One-Year Price Return Number of Shares to Buy
0      MMM       145.12              -5.218470                     N/A
1      AOS        57.97             -17.796368                     N/A
2      ABT        84.90             -37.017803                     N/A
3     ABBV       210.77              14.536465                     N/A
4      ACN       163.99             -48.380493                     N/A
..     ...          ...                    ...                     ...
498    XYL       109.44             -14.520037                     N/A
499    YUM       150.63               1.728916                     N/A
500   ZBRA       258.10             -14.144105                     N/A
501    ZBH        82.65             -14.749872                     N/A
502    ZTS        75.48             -53.704613                     N/A

[503 rows x 4 columns]

## Removing Low-Momentum Stocks

The investment strategy that we're building seeks to identify the 50 highest-momentum stocks in the S&P 500.

Because of this, the next thing we need to do is remove all the stocks in our DataFrame that fall below this momentum threshold. We'll sort the DataFrame by the stocks' one-year price return, and drop all stocks outside the top 50.

In [7]:
final_dataframe.sort_values('One-Year Price Return', ascending = False, inplace = True) 
final_dataframe = final_dataframe[:51] 
final_dataframe.reset_index(drop = True, inplace = True) 
final_dataframe

   Ticker  Stock Price  One-Year Price Return Number of Shares to Buy
0    SNDK      1382.72            3319.189000                     N/A
1    LITE      1001.81            1185.195700                     N/A
2     WDC       489.15             878.495670                     N/A
3      MU       776.01             691.846900                     N/A
4     STX       804.76             646.599850                     N/A
5    CIEN       591.57             628.175800                     N/A
6    SATS       135.11             477.640000                     N/A
7    INTC       115.93             435.226200                     N/A
8    COHR       404.94             415.190830                     N/A
9     FIX      2042.36             332.730930                     N/A
10    GLW       208.28             331.936980                     N/A
11    TER       356.55             330.980300                     N/A
12    AMD       449.70             283.801330                     N/A
13    VRT       376.23             254.800080                     N/A
14   LRCX       299.15             254.317180                     N/A
15    ALB       191.10             217.389130                     N/A
16    WBD        27.12             196.069850                     N/A
17   AMAT       440.56             166.086840                     N/A
18     ON       118.37             163.512920                     N/A
19    CAT       920.22             160.257930                     N/A
20    GEV      1090.53             154.761000                     N/A
21  GOOGL       401.07             141.332210                     N/A
22   KLAC      1892.94             139.258320                     N/A
23   GOOG       397.17             137.215550                     N/A
24    NEM       116.33             132.195620                     N/A
25    PWR       780.08             126.247856                     N/A
26   MPWR      1613.97             125.603870                     N/A
27   KEYS       361.55             118.591286                     N/A
28   DELL       247.89             117.085556                     N/A
29    CMI       716.45             114.198160                     N/A
30   GNRC       276.49             113.604760                     N/A
31    JBL       354.34             111.180640                     N/A
32    APA        37.11             110.972145                     N/A
33   MRNA        50.03             101.246980                     N/A
34    NUE       232.85             100.456260                     N/A
35   AKAM       155.67              99.500190                     N/A
36    EME       930.03              97.697850                     N/A
37   VTRS        17.26              95.248860                     N/A
38    HAL        41.29              94.305885                     N/A
39   AVGO       439.79              92.375656                     N/A
40   CASY       877.48              92.366540                     N/A
41    HPE        34.13              92.281685                     N/A
42    ADI       426.79              87.922160                     N/A
43   CSCO       115.53              81.593834                     N/A
44    VLO       244.77              80.322670                     N/A
45    IVZ        27.73              79.598450                     N/A
46     DD        50.60              74.457590                     N/A
47   STLD       234.68              74.120780                     N/A
48   NVDA       235.74              74.106346                     N/A
49    FCX        66.14              73.961070                     N/A
50   DDOG       202.84              72.380390                     N/A

## Calculating the Number of Shares to Buy

Just like in the last project, we now need to calculate the number of shares we need to buy. The one change we're going to make is wrapping this functionality inside a function, since we'll be using it again later in this Jupyter Notebook.

Since we've already done most of the work on this, try to complete the following two code cells without watching me do it first!

In [8]:
# def portfolio_input(): 
#     global portfoli_size 
#     portfolio_size = input("Enter the value of your portfolio:") 

#     try: 
#         val = float(portfolio_size) 
#     except ValueError: 
#         print("That's not a number! \n Try again:") 
#         portfolio_size = input("Ener the value of portfoli:") 


# portfolio_input()
# print(portfolio_size) 

def portfolio_input():
    while True:
        portfolio_size = input("Enter the value of your portfolio: ")

        try:
            return float(portfolio_size)
        except ValueError:
            print("That's not a number! Try again.")

portfolio_size = portfolio_input()
print(portfolio_size)

Enter the value of your portfolio:  10000000

10000000.0

In [9]:
# Force the column to be numeric so it can hold the result of math.floor 
final_dataframe['Number of Shares to Buy'] = pd.to_numeric(final_dataframe['Number of Shares to Buy'], errors='coerce')

position_size = float(portfolio_size) / len(final_dataframe.index) 
for i in range(0, len(final_dataframe.index)): 
    price = final_dataframe.loc[i, 'Stock Price'] 
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / price)

final_dataframe

   Ticker  Stock Price  One-Year Price Return  Number of Shares to Buy
0    SNDK      1382.72            3319.189000                    141.0
1    LITE      1001.81            1185.195700                    195.0
2     WDC       489.15             878.495670                    400.0
3      MU       776.01             691.846900                    252.0
4     STX       804.76             646.599850                    243.0
5    CIEN       591.57             628.175800                    331.0
6    SATS       135.11             477.640000                   1451.0
7    INTC       115.93             435.226200                   1691.0
8    COHR       404.94             415.190830                    484.0
9     FIX      2042.36             332.730930                     96.0
10    GLW       208.28             331.936980                    941.0
11    TER       356.55             330.980300                    549.0
12    AMD       449.70             283.801330                    436.0
13    VRT       376.23             254.800080                    521.0
14   LRCX       299.15             254.317180                    655.0
15    ALB       191.10             217.389130                   1026.0
16    WBD        27.12             196.069850                   7230.0
17   AMAT       440.56             166.086840                    445.0
18     ON       118.37             163.512920                   1656.0
19    CAT       920.22             160.257930                    213.0
20    GEV      1090.53             154.761000                    179.0
21  GOOGL       401.07             141.332210                    488.0
22   KLAC      1892.94             139.258320                    103.0
23   GOOG       397.17             137.215550                    493.0
24    NEM       116.33             132.195620                   1685.0
25    PWR       780.08             126.247856                    251.0
26   MPWR      1613.97             125.603870                    121.0
27   KEYS       361.55             118.591286                    542.0
28   DELL       247.89             117.085556                    790.0
29    CMI       716.45             114.198160                    273.0
30   GNRC       276.49             113.604760                    709.0
31    JBL       354.34             111.180640                    553.0
32    APA        37.11             110.972145                   5283.0
33   MRNA        50.03             101.246980                   3919.0
34    NUE       232.85             100.456260                    842.0
35   AKAM       155.67              99.500190                   1259.0
36    EME       930.03              97.697850                    210.0
37   VTRS        17.26              95.248860                  11360.0
38    HAL        41.29              94.305885                   4748.0
39   AVGO       439.79              92.375656                    445.0
40   CASY       877.48              92.366540                    223.0
41    HPE        34.13              92.281685                   5745.0
42    ADI       426.79              87.922160                    459.0
43   CSCO       115.53              81.593834                   1697.0
44    VLO       244.77              80.322670                    801.0
45    IVZ        27.73              79.598450                   7070.0
46     DD        50.60              74.457590                   3875.0
47   STLD       234.68              74.120780                    835.0
48   NVDA       235.74              74.106346                    831.0
49    FCX        66.14              73.961070                   2964.0
50   DDOG       202.84              72.380390                    966.0

## Building a Better (and More Realistic) Momentum Strategy

Real-world quantitative investment firms differentiate between "high quality" and "low quality" momentum stocks:

* High-quality momentum stocks show "slow and steady" outperformance over long periods of time
* Low-quality momentum stocks might not show any momentum for a long time, and then surge upwards.

The reason why high-quality momentum stocks are preferred is because low-quality momentum can often be cause by short-term news that is unlikely to be repeated in the future (such as an FDA approval for a biotechnology company).

To identify high-quality momentum, we're going to build a strategy that selects stocks from the highest percentiles of: 

* 1-month price returns
* 3-month price returns
* 6-month price returns
* 1-year price returns

Let's start by building our DataFrame. You'll notice that I use the abbreviation `hqm` often. It stands for `high-quality momentum`.

In [10]:
# hqm_columns = [ 
#     'Ticker', 
#     'Price', 
#     'Number of Shares to Buy', 
#     'One-Year Price Return', 
#     'One-Year Return Percentile', 
#     'Six-Month Price Return', 
#     'Six-Month Return Percentile', 
#     'Three-Month Price Return', 
#     'Three-Month Return Percentile', 
#     'One-Month Price Return', 
#     'One-Month Return Percentile', 
#     'HQM Score'
# ] 

# hqm_dataframe = pd.DataFrame(columns = hqm_columns) 

# for symbol in tickers_list:
#     try:
#         # Accessing the individual ticker object from our batch
#         ticker_info = tickers_data.tickers[symbol].info
#         price = ticker_info.get('currentPrice') or ticker_info.get('regularMarketPrice')
#         one_year_price_return = ticker_info.get('fiftyTwoWeekChangePercent') 
#         month_6_Change_Percent = ticker_infor.get('twoHundredDayAverageChangePercent') 
#         month_3_Change_Percent = ticker_info.get('fiftyDayAverageChangePercent') 
#         month_1_Change_Percent = ticket_info.get('') 
        
#         if price:
#             rows_list.append({
#                 'Ticker': symbol,
#                 'Stock Price': price,
#                 'One-Year Price Return': one_year_price_return,
#                 'Number of Shares to Buy': 'N/A'
#             })
#     except Exception as e:
#         # This skips tickers that might have been delisted mid-day or have errors
#         continue

import datetime

# 1. Define your universe and timeframes
tickers = stocks['Ticker'].tolist()
end_date = datetime.datetime.now()
start_date = end_date - datetime.timedelta(days=380) # Buffer to ensure we have a full year

# 2. Download historical data for the entire S&P 500 at once
# This is the "True" batch method for performance
print("Downloading historical data...")
ohlc_data = yf.download(tickers, start=start_date, end=end_date, interval='1d')['Close']

hqm_list = []

print("Calculating momentum metrics...")
for symbol in tickers:
    try:
        # Get price series for this stock and drop missing values
        series = ohlc_data[symbol].dropna()
        if len(series) < 250: continue # Skip if not enough history
        
        current_price = series.iloc[-1]
        
        # Calculate returns (Current Price / Historical Price) - 1
        # We use approximate trading days: 1yr=252, 6mo=126, 3mo=63, 1mo=21
        return_1yr = (current_price / series.iloc[-252]) - 1 if len(series) >= 252 else 0
        return_6mo = (current_price / series.iloc[-126]) - 1 if len(series) >= 126 else 0
        return_3mo = (current_price / series.iloc[-63]) - 1 if len(series) >= 63 else 0
        return_1mo = (current_price / series.iloc[-21]) - 1 if len(series) >= 21 else 0
        
        hqm_list.append({
            'Ticker': symbol,
            'Price': current_price,
            'Number of Shares to Buy': 'N/A',
            'One-Year Price Return': return_1yr,
            'One-Year Return Percentile': 'N/A',
            'Six-Month Price Return': return_6mo,
            'Six-Month Return Percentile': 'N/A',
            'Three-Month Price Return': return_3mo,
            'Three-Month Return Percentile': 'N/A',
            'One-Month Price Return': return_1mo,
            'One-Month Return Percentile': 'N/A',
            'HQM Score': 'N/A'
        })
    except Exception:
        continue

hqm_dataframe = pd.DataFrame(hqm_list)
hqm_dataframe

Downloading historical data...

[*********************100%***********************]  503 of 503 completed

Calculating momentum metrics...

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,MMM,145.119995,N/A,-0.000580,N/A,-0.144274,N/A,-0.155395,N/A,-0.036068,N/A,N/A
1,AOS,57.970001,N/A,-0.134018,N/A,-0.117254,N/A,-0.275421,N/A,-0.078704,N/A,N/A
2,ABT,84.900002,N/A,-0.326117,N/A,-0.333447,N/A,-0.241812,N/A,-0.110715,N/A,N/A
3,ABBV,210.770004,N/A,0.226536,N/A,-0.081471,N/A,-0.081993,N/A,0.008517,N/A,N/A
4,ACN,163.990005,N/A,-0.481265,N/A,-0.329166,N/A,-0.262451,N/A,-0.154691,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
497,XYL,109.440002,N/A,-0.116941,N/A,-0.265219,N/A,-0.142704,N/A,-0.125948,N/A,N/A
498,YUM,150.630005,N/A,0.057649,N/A,0.017881,N/A,-0.057581,N/A,-0.055730,N/A,N/A
499,ZBRA,258.100006,N/A,-0.137568,N/A,0.009425,N/A,-0.024639,N/A,0.107535,N/A,N/A
500,ZBH,82.650002,N/A,-0.123947,N/A,-0.077033,N/A,-0.140752,N/A,-0.127981,N/A,N/A
501,ZTS,75.480003,N/A,-0.505212,N/A,-0.372107,N/A,-0.401435,N/A,-0.363169,N/A,N/A

## Calculating Momentum Percentiles

We now need to calculate momentum percentile scores for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* `One-Year Price Return`
* `Six-Month Price Return`
* `Three-Month Price Return`
* `One-Month Price Return`

Here's how we'll do this:

In [11]:
# Force the column to be numeric so it can hold the result of math.floor 
hqm_dataframe['One-Year Return Percentile'] = pd.to_numeric(hqm_dataframe['One-Year Return Percentile'], errors='coerce')
hqm_dataframe['Six-Month Return Percentile'] = pd.to_numeric(hqm_dataframe['Six-Month Return Percentile'], errors='coerce')
hqm_dataframe['Three-Month Return Percentile'] = pd.to_numeric(hqm_dataframe['Three-Month Return Percentile'], errors='coerce')
hqm_dataframe['One-Month Return Percentile'] = pd.to_numeric(hqm_dataframe['One-Month Return Percentile'], errors='coerce')

time_periods = [
                'One-Year',
                'Six-Month',
                'Three-Month',
                'One-Month'
                ]

for row in hqm_dataframe.index:
    for time_period in time_periods:
        hqm_dataframe.loc[row, f'{time_period} Return Percentile'] = stats.percentileofscore(hqm_dataframe[f'{time_period} Price Return'], hqm_dataframe.loc[row, f'{time_period} Price Return'])/100

# Print each percentile score to make sure it was calculated properly
for time_period in time_periods:
    print(hqm_dataframe[f'{time_period} Return Percentile'])

#Print the entire DataFrame    
hqm_dataframe

0      0.366534
1      0.215139
2      0.095618
3      0.643426
4      0.029880
         ...
497    0.229084
498    0.438247
499    0.207171
500    0.221116
501    0.025896
Name: One-Year Return Percentile, Length: 502, dtype: float64
0      0.219124
1      0.243028
2      0.045817
3      0.286853
4      0.049801
         ...
497    0.099602
498    0.464143
499    0.444223
500    0.292829
501    0.029880
Name: Six-Month Return Percentile, Length: 502, dtype: float64
0      0.181275
1      0.049801
2      0.075697
3      0.336653
4      0.063745
         ...
497    0.199203
498    0.398406
499    0.503984
500    0.209163
501    0.005976
Name: Three-Month Return Percentile, Length: 502, dtype: float64
0      0.390438
1      0.221116
2      0.147410
3      0.607570
4      0.051793
         ...
497    0.109562
498    0.290837
499    0.836653
500    0.103586
501    0.003984
Name: One-Month Return Percentile, Length: 502, dtype: float64

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,MMM,145.119995,N/A,-0.000580,0.366534,-0.144274,0.219124,-0.155395,0.181275,-0.036068,0.390438,N/A
1,AOS,57.970001,N/A,-0.134018,0.215139,-0.117254,0.243028,-0.275421,0.049801,-0.078704,0.221116,N/A
2,ABT,84.900002,N/A,-0.326117,0.095618,-0.333447,0.045817,-0.241812,0.075697,-0.110715,0.147410,N/A
3,ABBV,210.770004,N/A,0.226536,0.643426,-0.081471,0.286853,-0.081993,0.336653,0.008517,0.607570,N/A
4,ACN,163.990005,N/A,-0.481265,0.029880,-0.329166,0.049801,-0.262451,0.063745,-0.154691,0.051793,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
497,XYL,109.440002,N/A,-0.116941,0.229084,-0.265219,0.099602,-0.142704,0.199203,-0.125948,0.109562,N/A
498,YUM,150.630005,N/A,0.057649,0.438247,0.017881,0.464143,-0.057581,0.398406,-0.055730,0.290837,N/A
499,ZBRA,258.100006,N/A,-0.137568,0.207171,0.009425,0.444223,-0.024639,0.503984,0.107535,0.836653,N/A
500,ZBH,82.650002,N/A,-0.123947,0.221116,-0.077033,0.292829,-0.140752,0.209163,-0.127981,0.103586,N/A
501,ZTS,75.480003,N/A,-0.505212,0.025896,-0.372107,0.029880,-0.401435,0.005976,-0.363169,0.003984,N/A

## Calculating the HQM Score

We'll now calculate our `HQM Score`, which is the high-quality momentum score that we'll use to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the `mean` function from Python's built-in `statistics` module.

In [12]:
# Force the column to be numeric so it can hold the result of float 
hqm_dataframe['HQM Score'] = pd.to_numeric(hqm_dataframe['HQM Score'], errors='coerce')

from statistics import mean 

for row in hqm_dataframe.index: 
    momentum_percentiles = [] 
    for time_period in time_periods: 
        momentum_percentiles.append(hqm_dataframe.loc[row, f'{time_period} Return Percentile'])
    hqm_dataframe.loc[row, 'HQM Score'] = mean(momentum_percentiles)

## Selecting the 50 Best Momentum Stocks

As before, we can identify the 50 best momentum stocks in our universe by sorting the DataFrame on the `HQM Score` column and dropping all but the top 50 entries.

In [13]:
hqm_dataframe.sort_values(by = 'HQM Score', ascending = False) 
hqm_dataframe = hqm_dataframe[:51] 
hqm_dataframe

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,MMM,145.119995,N/A,-0.000580,0.366534,-0.144274,0.219124,-0.155395,0.181275,-0.036068,0.390438,0.289343
1,AOS,57.970001,N/A,-0.134018,0.215139,-0.117254,0.243028,-0.275421,0.049801,-0.078704,0.221116,0.182271
2,ABT,84.900002,N/A,-0.326117,0.095618,-0.333447,0.045817,-0.241812,0.075697,-0.110715,0.147410,0.091135
3,ABBV,210.770004,N/A,0.226536,0.643426,-0.081471,0.286853,-0.081993,0.336653,0.008517,0.607570,0.468625
4,ACN,163.990005,N/A,-0.481265,0.029880,-0.329166,0.049801,-0.262451,0.063745,-0.154691,0.051793,0.048805
5,ADBE,237.009995,N/A,-0.406689,0.059761,-0.296811,0.079681,-0.102133,0.278884,-0.044931,0.330677,0.187251
6,AMD,449.700012,N/A,2.820082,0.976096,0.737031,0.948207,1.169111,0.996016,0.616114,0.994024,0.978586
7,AES,14.460000,N/A,0.214329,0.621514,0.052709,0.531873,-0.100842,0.286853,0.009537,0.613546,0.513446
8,AFL,116.389999,N/A,0.144500,0.525896,0.026252,0.488048,0.018261,0.619522,0.023569,0.655378,0.572211
9,A,113.260002,N/A,0.023939,0.386454,-0.249463,0.115538,-0.097699,0.300797,-0.042199,0.344622,0.286853
10,APD,299.869995,N/A,0.134209,0.509960,0.162121,0.711155,0.078681,0.745020,0.008848,0.609562,0.643924
11,ABNB,133.669998,N/A,-0.027501,0.336653,0.098447,0.613546,0.101525,0.778884,-0.030041,0.432271,0.540339
12,AKAM,155.669998,N/A,1.008386,0.926295,0.727747,0.944223,0.392895,0.950199,0.607995,0.992032,0.953187
13,ALB,191.100006,N/A,2.183606,0.970120,0.741766,0.950199,0.151629,0.822709,-0.113719,0.141434,0.721116
14,ARE,46.169998,N/A,-0.306467,0.099602,-0.115059,0.249004,-0.106506,0.268924,-0.037122,0.384462,0.250498
15,ALGN,160.529999,N/A,-0.144524,0.199203,0.132966,0.661355,-0.140494,0.211155,-0.132364,0.093625,0.291335
16,ALLE,131.139999,N/A,-0.063494,0.292829,-0.218218,0.147410,-0.266650,0.061753,-0.073347,0.241036,0.185757
17,LNT,72.449997,N/A,0.235688,0.647410,0.079922,0.561753,0.025318,0.637450,0.003056,0.573705,0.605080
18,ALL,216.449997,N/A,0.100305,0.474104,0.044747,0.513944,0.048360,0.697211,0.012063,0.623506,0.577191
19,GOOGL,401.070007,N/A,1.433698,0.958167,0.400770,0.884462,0.312810,0.922311,0.193590,0.920319,0.921315
20,GOOG,397.170013,N/A,1.389204,0.954183,0.383673,0.878486,0.298771,0.916335,0.193527,0.918327,0.916833
21,MO,72.410004,N/A,0.375893,0.776892,0.291485,0.842629,0.094771,0.770916,0.115029,0.848606,0.809761
22,AMZN,267.220001,N/A,0.270963,0.683267,0.094267,0.595618,0.344233,0.932271,0.070164,0.768924,0.745020
23,AMCR,38.590000,N/A,-0.136181,0.209163,-0.070239,0.302789,-0.219476,0.093625,-0.039572,0.358566,0.241036
24,AEE,109.599998,N/A,0.186911,0.577689,0.051258,0.525896,-0.005637,0.555777,-0.023869,0.462151,0.530378
25,AEP,128.600006,N/A,0.345700,0.752988,0.064217,0.545817,-0.003125,0.561753,-0.037352,0.376494,0.559263
26,AXP,312.769989,N/A,0.053144,0.426295,-0.156435,0.207171,-0.070344,0.366534,-0.039876,0.356574,0.339143
27,AIG,75.709999,N/A,-0.054688,0.304781,-0.018516,0.380478,-0.027002,0.496016,-0.032089,0.414343,0.398904
28,AMT,170.500000,N/A,-0.135489,0.213147,-0.051654,0.332669,-0.103573,0.272908,-0.045353,0.324701,0.285857
29,AWK,125.980003,N/A,-0.033797,0.328685,-0.009311,0.410359,-0.049579,0.424303,-0.029218,0.434263,0.399402
30,AMP,472.040009,N/A,-0.083054,0.262948,0.009827,0.446215,0.000198,0.569721,0.032210,0.681275,0.490040
31,AME,232.139999,N/A,0.302710,0.711155,0.183347,0.731076,0.011963,0.599602,0.008252,0.601594,0.660857
32,AMGN,336.230011,N/A,0.322169,0.727092,0.013960,0.452191,-0.089277,0.324701,-0.037666,0.370518,0.468625
33,APH,129.190002,N/A,0.519381,0.836653,-0.086140,0.280876,-0.117739,0.247012,-0.132720,0.091633,0.364044
34,ADI,426.790009,N/A,0.910332,0.916335,0.779483,0.958167,0.270028,0.900398,0.206303,0.926295,0.925299
35,AON,315.410004,N/A,-0.100262,0.241036,-0.096735,0.268924,-0.016966,0.521912,-0.056951,0.286853,0.329681
36,APA,37.110001,N/A,1.127432,0.936255,0.578637,0.918327,0.338051,0.928287,-0.014290,0.503984,0.821713
37,APO,135.520004,N/A,-0.046062,0.314741,0.022661,0.478088,0.087979,0.762948,0.121762,0.856574,0.603088
38,AAPL,298.209991,N/A,0.410037,0.790837,0.092493,0.591633,0.166959,0.840637,0.133200,0.868526,0.772908
39,AMAT,440.559998,N/A,1.552551,0.962151,0.915547,0.970120,0.242877,0.894422,0.129931,0.862550,0.922311
40,APP,485.160004,N/A,0.288469,0.699203,-0.170468,0.185259,0.242248,0.890438,0.040915,0.697211,0.618028
41,APTV,57.560001,N/A,-0.170844,0.189243,-0.304327,0.067729,-0.324413,0.023904,0.000695,0.563745,0.211155
42,ACGL,93.459999,N/A,0.028729,0.396414,0.018305,0.466135,-0.050010,0.418327,-0.037487,0.372510,0.413347
43,ADM,81.410004,N/A,0.705755,0.892430,0.432291,0.888446,0.180026,0.848606,0.185352,0.910359,0.884960
44,ARES,128.529999,N/A,-0.244495,0.123506,-0.146816,0.217131,-0.026891,0.498008,0.105920,0.834661,0.418327
45,ANET,147.809998,N/A,0.504887,0.826693,0.095051,0.597610,0.043930,0.689243,-0.081982,0.215139,0.582171
46,AJG,197.679993,N/A,-0.394376,0.067729,-0.222970,0.137450,-0.048768,0.426295,-0.117815,0.133466,0.191235
47,AIZ,252.720001,N/A,0.307693,0.715139,0.124732,0.651394,0.166759,0.836653,0.124950,0.860558,0.765936
48,T,24.650000,N/A,-0.027011,0.338645,-0.017543,0.382470,-0.131823,0.223108,-0.066288,0.258964,0.300797
49,ATO,180.869995,N/A,0.214404,0.623506,0.028619,0.490040,0.014644,0.607570,-0.037823,0.368526,0.522410
50,ADSK,233.860001,N/A,-0.208703,0.153386,-0.224962,0.135458,0.011418,0.595618,-0.038246,0.366534,0.312749

## Calculating the Number of Shares to Buy

We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a `for` loop to calculate the number of shares to buy for each stock in our investment universe.

In [15]:
portfolio_input()

Enter the value of your portfolio:  10000000

10000000.0

In [16]:
# Force the column to be numeric so it can hold the result of float 
hqm_dataframe['Number of Shares to Buy'] = pd.to_numeric(hqm_dataframe['Number of Shares to Buy'], errors='coerce')

position_size = float(portfolio_size) / len(hqm_dataframe.index)
for i in range(0, len(hqm_dataframe['Ticker'])-1):
    hqm_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / hqm_dataframe['Price'][i])
hqm_dataframe

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,MMM,145.119995,1351.0,-0.000580,0.366534,-0.144274,0.219124,-0.155395,0.181275,-0.036068,0.390438,0.289343
1,AOS,57.970001,3382.0,-0.134018,0.215139,-0.117254,0.243028,-0.275421,0.049801,-0.078704,0.221116,0.182271
2,ABT,84.900002,2309.0,-0.326117,0.095618,-0.333447,0.045817,-0.241812,0.075697,-0.110715,0.147410,0.091135
3,ABBV,210.770004,930.0,0.226536,0.643426,-0.081471,0.286853,-0.081993,0.336653,0.008517,0.607570,0.468625
4,ACN,163.990005,1195.0,-0.481265,0.029880,-0.329166,0.049801,-0.262451,0.063745,-0.154691,0.051793,0.048805
5,ADBE,237.009995,827.0,-0.406689,0.059761,-0.296811,0.079681,-0.102133,0.278884,-0.044931,0.330677,0.187251
6,AMD,449.700012,436.0,2.820082,0.976096,0.737031,0.948207,1.169111,0.996016,0.616114,0.994024,0.978586
7,AES,14.460000,13560.0,0.214329,0.621514,0.052709,0.531873,-0.100842,0.286853,0.009537,0.613546,0.513446
8,AFL,116.389999,1684.0,0.144500,0.525896,0.026252,0.488048,0.018261,0.619522,0.023569,0.655378,0.572211
9,A,113.260002,1731.0,0.023939,0.386454,-0.249463,0.115538,-0.097699,0.300797,-0.042199,0.344622,0.286853
10,APD,299.869995,653.0,0.134209,0.509960,0.162121,0.711155,0.078681,0.745020,0.008848,0.609562,0.643924
11,ABNB,133.669998,1466.0,-0.027501,0.336653,0.098447,0.613546,0.101525,0.778884,-0.030041,0.432271,0.540339
12,AKAM,155.669998,1259.0,1.008386,0.926295,0.727747,0.944223,0.392895,0.950199,0.607995,0.992032,0.953187
13,ALB,191.100006,1026.0,2.183606,0.970120,0.741766,0.950199,0.151629,0.822709,-0.113719,0.141434,0.721116
14,ARE,46.169998,4246.0,-0.306467,0.099602,-0.115059,0.249004,-0.106506,0.268924,-0.037122,0.384462,0.250498
15,ALGN,160.529999,1221.0,-0.144524,0.199203,0.132966,0.661355,-0.140494,0.211155,-0.132364,0.093625,0.291335
16,ALLE,131.139999,1495.0,-0.063494,0.292829,-0.218218,0.147410,-0.266650,0.061753,-0.073347,0.241036,0.185757
17,LNT,72.449997,2706.0,0.235688,0.647410,0.079922,0.561753,0.025318,0.637450,0.003056,0.573705,0.605080
18,ALL,216.449997,905.0,0.100305,0.474104,0.044747,0.513944,0.048360,0.697211,0.012063,0.623506,0.577191
19,GOOGL,401.070007,488.0,1.433698,0.958167,0.400770,0.884462,0.312810,0.922311,0.193590,0.920319,0.921315
20,GOOG,397.170013,493.0,1.389204,0.954183,0.383673,0.878486,0.298771,0.916335,0.193527,0.918327,0.916833
21,MO,72.410004,2707.0,0.375893,0.776892,0.291485,0.842629,0.094771,0.770916,0.115029,0.848606,0.809761
22,AMZN,267.220001,733.0,0.270963,0.683267,0.094267,0.595618,0.344233,0.932271,0.070164,0.768924,0.745020
23,AMCR,38.590000,5081.0,-0.136181,0.209163,-0.070239,0.302789,-0.219476,0.093625,-0.039572,0.358566,0.241036
24,AEE,109.599998,1789.0,0.186911,0.577689,0.051258,0.525896,-0.005637,0.555777,-0.023869,0.462151,0.530378
25,AEP,128.600006,1524.0,0.345700,0.752988,0.064217,0.545817,-0.003125,0.561753,-0.037352,0.376494,0.559263
26,AXP,312.769989,626.0,0.053144,0.426295,-0.156435,0.207171,-0.070344,0.366534,-0.039876,0.356574,0.339143
27,AIG,75.709999,2589.0,-0.054688,0.304781,-0.018516,0.380478,-0.027002,0.496016,-0.032089,0.414343,0.398904
28,AMT,170.500000,1150.0,-0.135489,0.213147,-0.051654,0.332669,-0.103573,0.272908,-0.045353,0.324701,0.285857
29,AWK,125.980003,1556.0,-0.033797,0.328685,-0.009311,0.410359,-0.049579,0.424303,-0.029218,0.434263,0.399402
30,AMP,472.040009,415.0,-0.083054,0.262948,0.009827,0.446215,0.000198,0.569721,0.032210,0.681275,0.490040
31,AME,232.139999,844.0,0.302710,0.711155,0.183347,0.731076,0.011963,0.599602,0.008252,0.601594,0.660857
32,AMGN,336.230011,583.0,0.322169,0.727092,0.013960,0.452191,-0.089277,0.324701,-0.037666,0.370518,0.468625
33,APH,129.190002,1517.0,0.519381,0.836653,-0.086140,0.280876,-0.117739,0.247012,-0.132720,0.091633,0.364044
34,ADI,426.790009,459.0,0.910332,0.916335,0.779483,0.958167,0.270028,0.900398,0.206303,0.926295,0.925299
35,AON,315.410004,621.0,-0.100262,0.241036,-0.096735,0.268924,-0.016966,0.521912,-0.056951,0.286853,0.329681
36,APA,37.110001,5283.0,1.127432,0.936255,0.578637,0.918327,0.338051,0.928287,-0.014290,0.503984,0.821713
37,APO,135.520004,1446.0,-0.046062,0.314741,0.022661,0.478088,0.087979,0.762948,0.121762,0.856574,0.603088
38,AAPL,298.209991,657.0,0.410037,0.790837,0.092493,0.591633,0.166959,0.840637,0.133200,0.868526,0.772908
39,AMAT,440.559998,445.0,1.552551,0.962151,0.915547,0.970120,0.242877,0.894422,0.129931,0.862550,0.922311
40,APP,485.160004,404.0,0.288469,0.699203,-0.170468,0.185259,0.242248,0.890438,0.040915,0.697211,0.618028
41,APTV,57.560001,3406.0,-0.170844,0.189243,-0.304327,0.067729,-0.324413,0.023904,0.000695,0.563745,0.211155
42,ACGL,93.459999,2097.0,0.028729,0.396414,0.018305,0.466135,-0.050010,0.418327,-0.037487,0.372510,0.413347
43,ADM,81.410004,2408.0,0.705755,0.892430,0.432291,0.888446,0.180026,0.848606,0.185352,0.910359,0.884960
44,ARES,128.529999,1525.0,-0.244495,0.123506,-0.146816,0.217131,-0.026891,0.498008,0.105920,0.834661,0.418327
45,ANET,147.809998,1326.0,0.504887,0.826693,0.095051,0.597610,0.043930,0.689243,-0.081982,0.215139,0.582171
46,AJG,197.679993,991.0,-0.394376,0.067729,-0.222970,0.137450,-0.048768,0.426295,-0.117815,0.133466,0.191235
47,AIZ,252.720001,775.0,0.307693,0.715139,0.124732,0.651394,0.166759,0.836653,0.124950,0.860558,0.765936
48,T,24.650000,7954.0,-0.027011,0.338645,-0.017543,0.382470,-0.131823,0.223108,-0.066288,0.258964,0.300797
49,ATO,180.869995,1084.0,0.214404,0.623506,0.028619,0.490040,0.014644,0.607570,-0.037823,0.368526,0.522410
50,ADSK,233.860001,NaN,-0.208703,0.153386,-0.224962,0.135458,0.011418,0.595618,-0.038246,0.366534,0.312749

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

In [27]:
writer = pd.ExcelWriter('momentum_strategy.xlsx', engine='xlsxwriter')
hqm_dataframe.to_excel(writer, sheet_name='Momentum Strategy', index = False)

## Creating the Formats We'll Need For Our .xlsx File

You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

Since we already built our formats in the last section of this course, I've included them below for you. Run this code cell before proceeding.

In [28]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0.000000',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

In [29]:
column_formats = { 
                    'A': ['Ticker', string_template],
                    'B': ['Price', dollar_template],
                    'C': ['Number of Shares to Buy', integer_template],
                    'D': ['One-Year Price Return', percent_template],
                    'E': ['One-Year Return Percentile', percent_template],
                    'F': ['Six-Month Price Return', percent_template],
                    'G': ['Six-Month Return Percentile', percent_template],
                    'H': ['Three-Month Price Return', percent_template],
                    'I': ['Three-Month Return Percentile', percent_template],
                    'J': ['One-Month Price Return', percent_template],
                    'K': ['One-Month Return Percentile', percent_template],
                    'L': ['HQM Score', integer_template]
                    }

for column in column_formats.keys():
    writer.sheets['Momentum Strategy'].set_column(f'{column}:{column}', 20, column_formats[column][1])
    writer.sheets['Momentum Strategy'].write(f'{column}1', column_formats[column][0], string_template)

## Saving Our Excel Output

As before, saving our Excel output is very easy:

In [31]:
writer.close()